### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by lboening** [MathieuBuisson/PSGithubSearch#4]
Would you be able to create a release? I can grab the release.zip file rather quickly with Invoke-WebRequest -uri 'https://github.com/MathieuBuisson/PSGithubSearch/archive/0.2.1.zip' (or something to that effect.

Example uri:
'https://github.com/darkoperator/Posh-SSH/archive/1.7.5.zip'

**Comment by MathieuBuisson** [comment]
Hi lboening,

I created a release from the current Master branch.
You can download it from the following URL:
https://github.com/MathieuBuisson/PSGithubSearch/archive/1.0.0.zip

Thanks.
